use base64+zstd for account data encoding by default
hubbleprotocol/solana-shadow pull request #18
Opened 2022-02-16 00:37 UTC by dovahcrow

The jsonParsed encoding won't work if the account data can be parsed by the RPC node. For example, the spl-token account will be actually parsed! The notification from WS becomes 

```json
{
    "jsonrpc": "2.0",
    "method": "accountNotification",
    "params": {
        "result": {
            "context": {
                "slot": 114915064
            },
            "value": {
                "lamports": 2039280,
                "data": {
                    "program": "spl-token",
                    "parsed": {
                        "info": {
                            "isNative": false,
                            "mint": "USDhTjkUXFfigLELiFpbBnpLmEm4aXHvdY2kDSadJDH",
                            "owner": "8dyR4YwFHzh2Pxmgs9TPst5Mu4kkES5tu8w6SuhdEyUG",
                            "state": "initialized",
                            "tokenAmount": {
                                "amount": "5771086231612606",
                                "decimals": 9,
                                "uiAmount": 5771086.231612606,
                                "uiAmountString": "5771086.231612606"
                            }
                        },
                        "type": "account"
                    },
                    "space": 165
                },
                "owner": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
                "executable": false,
                "rentEpoch": 266
            }
        },
        "subscription": 10447
    }
}
```
and cannot be deserialized into the AccountRepresentation struct.

Choosing base64+zstd because it is compressed and should save network bandwidth theoretically (which is the bottleneck).

2022-02-17 23:38 UTC, y2kappa commented
@boymaas @karim-agha

2022-02-17 23:38 UTC, y2kappa commented
@dovahcrow let us know when it’s ready

2022-02-26 11:23 UTC, dovahcrow commented
> @dovahcrow let us know when it’s ready

It's ready.

2022-03-07 11:36 UTC, karim-agha approved these changes
Not a very thorough review on my part, but lgtm on first sight. Maybe it's good to have one more pair of eyes looking at it.

2022-03-17 11:41 UTC, y2kappa commented
@boymaas @oeble ping

2022-03-17 11:45 UTC, boymaas commented
Looks good, a keep alive and `base64+zstd`. Approved from my part

2022-03-17 11:46 UTC, boymaas approved these changes

2022-03-17 12:40 UTC, oeble approved these changes

2022-03-17 13:29 UTC, y2kappa requested changes
@dovahcrow

2022-03-17 13:29 UTC, y2kappa commented on Cargo.toml
> +version = "0.2.4"
please bump the version

2022-03-18 02:04 UTC, dovahcrow commented on Cargo.toml
> +version = "0.2.4"
done

2022-03-26 02:31 UTC, merged